const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const LS='queenLifeV7.';const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(LS+k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(LS+k,JSON.stringify(v)),del:k=>localStorage.removeItem(LS+k)};
const todayKey=()=>new Date().toISOString().slice(0,10);let selectedMood=null;let timerInt=null;let deferredPrompt=null;let dbp=null;let minMode=false;
const defaultRituals=[['07:30','Aelin Rise','Water, curtains, bed, oath.'],['07:45','Feyre Morning Page','Mood + one beautiful thing.'],['08:00','Body Is Sacred','Workout, walk, mobility, or low-energy version.'],['12:30','Court Meal','Protein + carb/fiber + color + fat/flavor + water.'],['15:30','Jude Strategy','Next smart visible move.'],['18:30','Training / Realm Sprint','Workout, walk, clean, study, or admin.'],['21:30','Night Court Reset','10-minute tidy, shower/skincare, tomorrow outfit.'],['22:30','Phone Curfew','Read, journal 3 wins, phone away.'],['23:00','Sleep Spell','Lights down. Rest is training.']];
const arcs=[['Foundation Arc','stabilize sleep/wake, water, basic movement, no perfection'],['Body + Realm Arc','build strength, clean your space, create outfit rhythm'],['Strategy Arc','boundaries, study/work sprints, finances, courageous messages'],['Embodiment Arc','choose identity, polish systems, review, simplify']];
const vibes={Aelin:{emoji:'🔥',armor:'sleek hair, black/cream/gold, boots, bold jewelry, one red or gold detail',mantra:'I do the brave thing before I feel brave.'},Feyre:{emoji:'🌙',armor:'soft layers, silver/blue/cream, cozy texture, braid or loose waves, luminous skin',mantra:'Softness is not weakness.'},Poppy:{emoji:'🗡️',armor:'ivory/white, structured comfort, pearls/ribbon, flushed cheeks, curious eyes',mantra:'I am allowed to want a full life.'},Jude:{emoji:'♟️',armor:'dark green/black, blazer, belt, rings, clean nails, sharp shoes',mantra:'I do not need permission to be strategic.'},Academic:{emoji:'📚',armor:'knit, trousers/skirt, loafers/boots, tote, clean lines, pen/book accessory',mantra:'I become dangerous by learning.'},Cozy:{emoji:'🕯️',armor:'soft knit, leggings/trousers, warm socks, gentle hair, comforting scent',mantra:'I can recover without disappearing.'},'Dark Fae':{emoji:'🦇',armor:'black, deep green, silver, leather texture, winged liner/rings, mysterious silhouette',mantra:'I am allowed to take up space.'},'Soft Court':{emoji:'🦢',armor:'cream, blush, soft gold, ballet flats/boots, delicate details',mantra:'I can be gentle and still be disciplined.'}};
const questsBase=[['Body proof','Do today’s workout OR low-energy swap.'],['Mind proof','Write one honest sentence or thought reset.'],['Realm proof','Clean/reset one 5-minute zone.'],['Armor proof','Wear one intentional detail.'],['Nourishment proof','Eat one court meal or emergency meal.'],['Connection proof','Send one kind/check-in/brave message.']];
const minQuests=[['Water + light','Drink water and open curtains/window.'],['Teeth or shower','One hygiene proof.'],['5-minute movement','Stretch, walk, dance, or mobility.'],['One real bite','Eat something with substance.'],['Phone away at night','10 minutes without scrolling before sleep.']];
const timelineTasks=[['07:30','Open the gates','Water, curtains, make bed badly if needed.'],['07:45','Choose the queen action','Mood, top 1 priority, outfit vibe.'],['08:00','Body ritual','Workout, walk, mobility, or minimum movement.'],['12:30','Nourish','Court meal + step outside/window reset.'],['15:30','Strategy check','What is the next smart visible move?'],['18:30','Realm/body sprint','Training, cleaning, study or admin.'],['21:30','Close the court','Tidy, skincare/shower, prep outfit.'],['22:30','Exit the scroll','Read or journal. Phone away.']];
const morning=['Water before phone','Open light/curtains','Make bed in under 90 seconds','Choose today’s court: Aelin/Feyre/Poppy/Jude','Write: mood, main quest, one beautiful thing','Move for at least 5 minutes'];
const night=['10-minute tidy reset','Shower/skincare/teeth','Lay out tomorrow outfit or one armor piece','Write 3 wins, even tiny ones','Put phone away or grayscale mode','Read fiction/nonfiction until sleepy'];
const minimum=['Water','Light/window','Teeth or shower','5-minute movement','One real bite of food','One message to a person','Phone away for 10 minutes before sleep'];
const mealCols={Protein:['eggs','Greek yogurt/skyr','tuna/sardines','chicken','tofu','lentils/beans','cheese','protein leftovers'],CarbFiber:['rice','pasta','potatoes','bread/wrap','oats','couscous','beans','fruit'],Color:['frozen vegetables','salad','tomatoes','carrots','berries','apple','soup vegetables','peppers'],FatFlavor:['olive oil','avocado','nuts','peanut butter','pesto','butter','sauce','dark chocolate square'],EasyMeals:['eggs + toast + fruit','tuna rice bowl','yogurt + oats + berries','wrap with protein + salad','pasta + pesto + vegetables','soup + bread + cheese','tofu/beans + rice + sauce','omelette + frozen vegetables']};
const emergencyMeals=['Toast + eggs or cheese','Yogurt/skyr + cereal/oats + fruit','Microwave rice + tuna/beans + sauce','Soup + bread','Pasta + pesto + frozen veg','Sandwich/wrap + water','Banana + peanut butter + yogurt','Leftovers arranged like a bowl'];
const grocery=['eggs','Greek yogurt/skyr','rice/pasta/oats','bread/wraps','tuna/beans/lentils/tofu/chicken','frozen vegetables','fruit','salad/tomatoes/carrots','olive oil/pesto/sauce','tea/coffee','dark chocolate or favorite comfort snack'];
const workouts=[
{day:1,court:'Aelin',name:'Lower Body Fire',intent:'Strengthen legs/glutes and build grounded confidence.',warm:'2 min march + hip circles + 10 bodyweight good mornings',moves:[['Squat','3 rounds × 8–12 reps'],['Reverse lunge','3 × 6–10 each leg'],['Glute bridge','3 × 12–18'],['Calf raise','2 × 15–20'],['Wall sit','2 × 20–45 sec']],fin:'3-minute brisk walk or stair climb',low:'1 round only + 5-minute walk.'},
{day:2,court:'Feyre',name:'Mobility + Walk',intent:'Recover, regulate, keep the promise without overdoing it.',warm:'Neck rolls + shoulder circles + cat-cow',moves:[['Walk','20–35 minutes easy'],['Hip flexor stretch','45 sec each side'],['Hamstring stretch','45 sec each side'],['Child’s pose breathing','5 slow breaths'],['Thoracic openers','8 each side']],fin:'Make tea/water and breathe at a window.',low:'5-minute walk + one stretch.'},
{day:3,court:'Jude',name:'Upper + Core Strategy',intent:'Posture, arms, core, and discipline.',warm:'Arm circles + wall push-ups + dead bug practice',moves:[['Incline/knee push-up','3 × 6–12'],['Backpack row','3 × 8–12'],['Dead bug','3 × 8 each side'],['Plank','3 × 15–35 sec'],['Superman hold','2 × 20 sec']],fin:'One 60-second posture walk: shoulders down, chin level.',low:'2 sets wall push-ups + dead bugs.'},
{day:4,court:'Poppy',name:'Curiosity Cardio',intent:'Move playfully and remember your body is alive.',warm:'2 songs gentle dancing or easy stepping',moves:[['Dance/walk intervals','10 rounds: 40 sec move + 20 sec easy'],['Side steps','2 × 45 sec'],['Step-back reach','2 × 8 each'],['Standing crunch','2 × 12 each'],['Breathing reset','1 minute']],fin:'Write one thing your body did for you.',low:'One song dance party.'},
{day:5,court:'Aelin',name:'Full Body Court Circuit',intent:'Combine strength and stamina.',warm:'3 min easy walk + 10 squats + 10 arm circles',moves:[['Squat','3 × 10'],['Push-up variation','3 × 8'],['Backpack row','3 × 10'],['Glute bridge','3 × 15'],['Mountain climber slow','3 × 20 total']],fin:'2-minute fast walk or stairs',low:'1 circuit, slow and clean.'},
{day:6,court:'Feyre',name:'Beauty Walk + Stretch',intent:'Aesthetic recovery and nervous-system care.',warm:'Put on a playlist/audiobook',moves:[['Outdoor walk','25–45 minutes if possible'],['Ankle circles','10 each'],['Forward fold','60 sec'],['Figure-4 stretch','45 sec each'],['Wall chest stretch','45 sec each']],fin:'Take one beautiful photo or notice one color.',low:'Walk to the end of the street/window breath.'},
{day:0,court:'Jude',name:'Reset + Prep',intent:'Prepare the week like a strategist.',warm:'5-minute tidy',moves:[['Laundry/outfit prep','10–20 min'],['Meal basics check','5 min'],['Calendar check','5 min'],['Gentle stretch','8 min'],['Plan top 3 quests','5 min']],fin:'Lay out Monday armor.',low:'Write tomorrow’s first move only.'}
];
const progressions=[['Week 1','Learn form. Do the lower end of reps. Rest 60–90 sec.'],['Week 2','Add one round to one move OR add 5 min walking.'],['Week 3','Slow tempo: 3 seconds down on squats/pushups/bridges.'],['Week 4','Add intensity: less rest or harder variation.'],['Week 5','Repeat Week 1 numbers but cleaner; add range of motion.'],['Week 6','Add one backpack weight move where safe.'],['Week 7','Add a finisher: 4 minutes brisk walk/dance/stairs.'],['Week 8','Deload/test: choose favorites, record what improved.']];
const exerciseCues={Squat:'Feet grounded, knees track over toes, chest proud, sit between hips.',Lunge:'Small enough step to control. Front foot heavy. Use wall/chair for balance.',Bridge:'Ribs down, squeeze glutes at top, do not arch lower back.',Pushup:'Hands under shoulders, body like a plank. Use wall/table/knees as needed.',Row:'Pull elbows back, squeeze shoulder blades, keep neck relaxed.',Plank:'Ribs tucked, glutes lightly on, breathe. Stop before form collapses.',Walk:'You should be able to speak in short sentences. Outside light is a bonus.',Stretch:'Mild tension only, never sharp pain.'};
const stateMenu=[['Frozen','Make it smaller: sit up, water, one text, 2-minute tidy.'],['Anxious','Exhale longer than inhale. Write facts vs story. Move legs for 3 minutes.'],['Sad','Warm shower, comfort show/book timer, one nourishing meal, message someone safe.'],['Angry','Fast walk/stairs, write the unsent message, choose the clean boundary.'],['Overstimulated','Dim lights, headphones/noise reduction, clean one visual surface, phone away.']];
const resetSteps=['Feet on floor. Name 5 things you see.','Drink water or hold something cold/warm.','Exhale slowly 5 times.','Ask: what is fact, what is fear?','Do one visible action under 2 minutes.','Text a safe person if you need support.'];
const realm=[['Room reset','Daily: clear floor + one surface. Weekly: laundry, sheets, trash, desk.'],['Study/work','One 25-minute sprint before reward scrolling. Define the first tiny move.'],['Admin','Capture tasks in one list. Do one annoying thing every other day.'],['Money','Check balance, upcoming payments, spending leak, one future-you action.'],['Beauty maintenance','Nails, brows, hair wash, skincare, clothes prep: rotate small care tasks.'],['Social court','One genuine message, one boundary, one plan/date/friendship action.']];
const money=['Open bank app without judgment','Check upcoming payments','Write one thing you spent on that was worth it','Write one leak to reduce','Move/save even €1 if possible, or plan the next income action'];
const vibeFormula=Object.entries(vibes).map(([k,v])=>({vibe:k,...v}));
function init(){store.set('version','v7');setupTabs();setupInstall();registerSW();initDB();renderAll();bind();scheduleLocalReminders()}
function renderAll(){renderBrief();renderToday();renderRituals();renderBody();renderMeals();renderMind();renderStyle();renderRealm();renderReview();renderSettings()}
function dayNum(){let s=store.get('start',null);if(!s){s=todayKey();store.set('start',s)}const a=new Date(s+'T00:00:00'),b=new Date(todayKey()+'T00:00:00');return Math.max(1,Math.min(56,Math.floor((b-a)/86400000)+1))}
function weekNum(){return Math.min(8,Math.ceil(dayNum()/7))}function arc(){return arcs[Math.min(3,Math.floor((dayNum()-1)/14))]}
function todayWorkout(){return workouts.find(w=>w.day===new Date().getDay())||workouts[0]}
function completions(){return store.get('done',{})}function saveDone(c){store.set('done',c)}
function renderBrief(){const w=todayWorkout(),v=vibes[w.court],m=mealCols.EasyMeals[new Date().getDate()%mealCols.EasyMeals.length];$('#briefTitle').textContent=`${v.emoji} ${w.court} day — ${w.name}`;$('#briefText').textContent=`${w.intent} Armor: ${v.armor}. Meal: ${m}. Mantra: ${v.mantra}`}
function renderToday(){const d=dayNum(),a=arc();$('#dayNum').textContent=d;$('#arcName').textContent=a[0];$('#todayTitle').textContent=a[1];renderMood();renderTimeline();renderQuests();renderWorkoutToday();updateProgress()}
function renderMood(){const moods=['😶‍🌫️','😢','😐','🙂','🔥'];$('#moodButtons').innerHTML=moods.map(m=>`<button data-mood="${m}">${m}</button>`).join('');$$('#moodButtons button').forEach(b=>b.onclick=()=>{selectedMood=b.dataset.mood;$$('#moodButtons button').forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
function currentQuestSet(){return minMode?minQuests:questsBase}
function renderQuests(){const box=$('#quests');box.innerHTML='';const c=completions(),key=todayKey();currentQuestSet().forEach((q,i)=>{const node=$('#questTemplate').content.cloneNode(true);const inp=$('input',node),strong=$('strong',node),small=$('small',node);const id=`${key}.q${i}.${minMode?'min':'full'}`;inp.checked=!!c[id];strong.textContent=q[0];small.textContent=q[1];inp.onchange=()=>{const c=completions();c[id]=inp.checked;saveDone(c);updateProgress()};box.appendChild(node)})}
function renderTimeline(){const box=$('#timeline'),c=completions(),key=todayKey();box.innerHTML=timelineTasks.map((t,i)=>{const id=`${key}.t${i}`;return `<div class="timeblock ${c[id]?'done':''}"><div class="time">${timeForIndex(i,t[0])}</div><div><strong>${t[1]}</strong><br><span class="muted">${t[2]}</span></div><button class="ghost timelineDone" data-id="${id}">${c[id]?'Done ✓':'Done'}</button></div>`}).join('');$$('.timelineDone').forEach(b=>b.onclick=()=>{const c=completions();c[b.dataset.id]=!c[b.dataset.id];saveDone(c);renderTimeline();updateProgress()})}
function timeForIndex(i,fallback){const r=store.get('rituals',defaultRituals);return r[i]?.[0]||fallback}
function renderWorkoutToday(){const w=todayWorkout(),v=vibes[w.court],p=progressions[weekNum()-1];$('#workoutName').textContent=`${v.emoji} ${w.name}`;$('#workoutIntent').textContent=`${w.intent} ${p[0]}: ${p[1]}`;$('#workoutSteps').innerHTML=`<div class="mini-item"><strong>Warm-up</strong><br><span class="muted">${w.warm}</span></div>`+w.moves.map(m=>`<div class="mini-item"><strong>${m[0]}</strong><br><span class="muted">${m[1]}</span></div>`).join('')+`<div class="mini-item"><strong>Finisher</strong><br><span class="muted">${w.fin}</span></div>`;$('#workoutLow').textContent=w.low;$('#armorTitle').textContent=`${v.emoji} ${w.court} armor`;$('#armorText').textContent=v.armor;$('#mealText').textContent='Meal idea: '+mealCols.EasyMeals[new Date().getDate()%mealCols.EasyMeals.length];$('#markWorkout').textContent=store.get('workouts',[]).includes(todayKey())?'Complete ✓':'Mark complete'}
function updateProgress(){const c=completions(),key=todayKey();const today=Object.keys(c).filter(k=>k.startsWith(key)&&c[k]).length;const total=currentQuestSet().length+timelineTasks.length;$('#progress').style.width=Math.min(100,today/total*100)+'%';const xp=Object.values(c).filter(Boolean).length*5+store.get('workouts',[]).length*20+store.get('thoughts',[]).length*10;$('#xp').textContent=xp;$('#level').textContent=Math.floor(xp/150)+1;$('#streak').textContent=streak()}
function streak(){const c=completions();let s=0;for(let i=0;i<90;i++){const d=new Date();d.setDate(d.getDate()-i);const k=d.toISOString().slice(0,10);const ok=Object.keys(c).some(x=>x.startsWith(k)&&c[x])||store.get('workouts',[]).includes(k);if(ok)s++;else if(i>0)break}return s}
function renderRituals(){const rituals=store.get('rituals',defaultRituals);$('#ritualList').innerHTML=rituals.map(r=>`<div class="ritual"><span class="time">${r[0]}</span><h3>${r[1]}</h3><p class="muted">${r[2]}</p></div>`).join('');$('#morningList').innerHTML=morning.map(x=>`<li>${x}</li>`).join('');$('#nightList').innerHTML=night.map(x=>`<li>${x}</li>`).join('');$('#minimumList').innerHTML=minimum.map(x=>`<div class="mini-item">${x}</div>`).join('')}
function renderBody(){const sel=$('#weekSelect');sel.innerHTML=progressions.map((p,i)=>`<option value="${i+1}" ${i+1===weekNum()?'selected':''}>${p[0]}</option>`).join('');renderWeek(weekNum());sel.onchange=()=>renderWeek(Number(sel.value));$('#exerciseLibrary').innerHTML=Object.entries(exerciseCues).map(([k,v])=>`<details><summary>${k}</summary><p class="muted">${v}</p></details>`).join('')}
function renderWeek(wk){const p=progressions[wk-1];$('#weekPlan').innerHTML=workouts.map(w=>`<article class="training-day ${w.day===new Date().getDay()?'today':''}"><p class="small-label">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][w.day]} · ${vibes[w.court].emoji} ${w.court}</p><h3>${w.name}</h3><p class="muted"><strong>${p[0]}:</strong> ${p[1]}</p><p>${w.intent}</p><ul>${w.moves.map(m=>`<li><strong>${m[0]}:</strong> ${m[1]}</li>`).join('')}</ul><p class="muted"><strong>Low energy:</strong> ${w.low}</p></article>`).join('')}
function renderMeals(){$('#mealBuilder').innerHTML=Object.entries(mealCols).filter(([k])=>k!=='EasyMeals').map(([k,arr])=>`<div class="meal-col"><h3>${k}</h3><p class="muted">${arr.join(' · ')}</p></div>`).join('');$('#emergencyMeals').innerHTML=emergencyMeals.map(x=>`<div class="mini-item">${x}</div>`).join('');$('#groceryList').innerHTML=grocery.map(x=>`<div class="mini-item">${x}</div>`).join('')}
function renderMind(){$('#resetSteps').innerHTML=resetSteps.map((x,i)=>`<div class="mini-item"><strong>${i+1}.</strong> ${x}</div>`).join('');$('#stateMenu').innerHTML=stateMenu.map(x=>`<div class="mini-item"><strong>${x[0]}</strong><br><span class="muted">${x[1]}</span></div>`).join('')}
function renderStyle(){renderCloset();$('#vibeFormulas').innerHTML=vibeFormula.map(v=>`<article class="training-day"><p class="small-label">${v.emoji} ${v.vibe}</p><h3>Armor formula</h3><p class="muted">${v.armor}</p><p>${v.mantra}</p></article>`).join('')}
function renderRealm(){$('#realmQuests').innerHTML=realm.map(x=>`<article class="training-day"><h3>${x[0]}</h3><p class="muted">${x[1]}</p></article>`).join('');$('#moneySteps').innerHTML=money.map((x,i)=>`<div class="mini-item"><strong>${i+1}.</strong> ${x}</div>`).join('')}
function renderReview(){const thoughts=store.get('thoughts',[]),reviews=store.get('reviews',[]);$('#stats').innerHTML=`<div class="mini-item">Workouts logged: ${store.get('workouts',[]).length}</div><div class="mini-item">Mood entries: ${store.get('moods',[]).length}</div><div class="mini-item">Thought resets: ${thoughts.length}</div><div class="mini-item">Closet items: ${store.get('closetMeta',[]).length}</div>`;$('#archive').innerHTML=[...reviews,...thoughts].slice(0,10).map(x=>`<div class="mini-item"><strong>${x.date}</strong><br><span class="muted">${x.text||x.action||x.truth||''}</span></div>`).join('')||'<p class="muted">Nothing saved yet.</p>'}
function renderSettings(){const r=store.get('rituals',defaultRituals);$('#settingsRituals').innerHTML=r.map((x,i)=>`<label>${x[1]}<input data-rit="${i}" value="${x[0]}" type="time"></label>`).join('')}
function bind(){
$('#minimumDay').onclick=()=>{minMode=!minMode;$('#minimumDay').textContent=minMode?'Full day mode':'Minimum day mode';renderQuests();toast(minMode?'Minimum day mode on. Still counts.':'Full quests restored.')};
$('#saveMood').onclick=()=>{const arr=store.get('moods',[]);arr.unshift({date:new Date().toLocaleString(),mood:selectedMood||'unmarked',note:$('#moodNote').value.trim()});store.set('moods',arr.slice(0,200));$('#moodNote').value='';toast('Mood saved.');renderReview()};
$('#resetToday').onclick=()=>{if(!confirm('Reset today?'))return;const c=completions(),k=todayKey();Object.keys(c).forEach(x=>{if(x.startsWith(k))delete c[x]});saveDone(c);renderToday()};
$('#markWorkout').onclick=()=>{const a=store.get('workouts',[]);if(!a.includes(todayKey()))a.push(todayKey());store.set('workouts',a);renderWorkoutToday();updateProgress();renderReview();toast('Workout proof logged.')};
$('#startWorkoutTimer').onclick=()=>startTimer(30);$$('.timerBtn').forEach(b=>b.onclick=()=>startTimer(Number(b.dataset.secs)));$('#stopTimer').onclick=()=>stopTimer();
$('#randomMeal').onclick=()=>{$('#mealIdea').textContent=mealCols.EasyMeals[Math.floor(Math.random()*mealCols.EasyMeals.length)]};$('#copyGrocery').onclick=()=>copy(grocery.join('\n'));
$('#copyReset').onclick=()=>copy(resetSteps.join('\n'));$('#saveThought').onclick=saveThought;$('#overwhelm').onclick=()=>openTab('mind');
$('#planOutfitToday').onclick=()=>openTab('style');$('#saveItem').onclick=saveItem;$('#buildOutfit').onclick=buildOutfit;$('#exportCloset').onclick=()=>copy(JSON.stringify(store.get('closetMeta',[]),null,2));
$('#startSprint').onclick=()=>{const task=$('#sprintTask').value||'main task';const move=$('#sprintMove').value||'first tiny move';$('#sprintStatus').textContent=`25 minutes: ${task}. First move: ${move}. No negotiation.`;startTimer(25*60)};
$('#saveReview').onclick=()=>{const arr=store.get('reviews',[]);arr.unshift({date:new Date().toLocaleString(),text:`Worked: ${$('#worked').value} | Drained: ${$('#drained').value} | Simplify: ${$('#simplify').value}`});store.set('reviews',arr);['worked','drained','simplify'].forEach(id=>$('#'+id).value='');toast('Review saved.');renderReview()};
$('#saveSettings').onclick=()=>{const r=store.get('rituals',defaultRituals);$$('[data-rit]').forEach(inp=>r[Number(inp.dataset.rit)][0]=inp.value);store.set('rituals',r);renderRituals();renderTimeline();scheduleLocalReminders();toast('Times saved.')};
$('#enableNotifications').onclick=enableNotif;$('#testNotification').onclick=()=>notify('Queen OS test','Your Samsung can show Queen OS notifications.');$('#copyBrief').onclick=()=>copy($('#briefTitle').textContent+'\n'+$('#briefText').textContent);
$('#exportData').onclick=exportData;$('#importData').onclick=()=>$('#importFile').click();$('#importFile').onchange=importData;$('#resetAll').onclick=()=>{if(confirm('Delete all Queen OS local data?')){Object.keys(localStorage).filter(k=>k.startsWith(LS)).forEach(k=>localStorage.removeItem(k));location.reload()}}
}
function saveThought(){const arr=store.get('thoughts',[]);arr.unshift({date:new Date().toLocaleString(),sit:$('#sit').value,story:$('#story').value,truth:$('#truth').value,action:$('#action').value});store.set('thoughts',arr.slice(0,100));['sit','story','truth','action'].forEach(id=>$('#'+id).value='');toast('Thought alchemy saved.');renderReview();updateProgress()}
function setupTabs(){$$('.tab').forEach(t=>t.onclick=()=>openTab(t.dataset.tab))}function openTab(id){$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===id));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id));scrollTo({top:0,behavior:'smooth'})}
function startTimer(sec){stopTimer();let left=sec;$('#timer').textContent=fmt(left);timerInt=setInterval(()=>{left--;$('#timer').textContent=fmt(left);if(left<=0){stopTimer(false);notify('Timer complete','Your Queen OS timer finished.')}},1000)}function stopTimer(reset=true){clearInterval(timerInt);timerInt=null;if(reset)$('#timer').textContent='00:00'}function fmt(s){return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}function copy(txt){navigator.clipboard?.writeText(txt);toast('Copied.')}
function notify(title,body){if(Notification.permission==='granted')new Notification(title,{body,icon:'assets/icon-192.png'});else toast(body)}async function enableNotif(){if(!('Notification'in window)){toast('Notifications not supported here.');return}const p=await Notification.requestPermission(); if(p==='granted') scheduleLocalReminders(); toast(p==='granted'?'Notifications enabled.':'Notification permission not granted.')}
function scheduleLocalReminders(){window._reminders?.forEach(clearTimeout);window._reminders=[];if(!('Notification'in window)||Notification.permission!=='granted')return;const r=store.get('rituals',defaultRituals);r.forEach(([time,title,body])=>{const [h,m]=time.split(':').map(Number);const now=new Date(),due=new Date();due.setHours(h,m,0,0);if(due<now)due.setDate(due.getDate()+1);const ms=due-now;window._reminders.push(setTimeout(()=>notify(title,body),ms))})}
function initDB(){dbp=new Promise((res,rej)=>{const q=indexedDB.open('QueenLifeCloset',1);q.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains('images'))db.createObjectStore('images',{keyPath:'id'})};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function saveItem(){const file=$('#photo').files[0];const id='piece-'+Date.now();const meta={id,name:$('#itemName').value||'Untitled piece',cat:$('#itemCat').value,vibe:$('#itemVibe').value,tags:$('#itemTags').value,date:new Date().toISOString()};if(file){const db=await dbp;const tx=db.transaction('images','readwrite');tx.objectStore('images').put({id,blob:file});await new Promise(r=>tx.oncomplete=r)}const arr=store.get('closetMeta',[]);arr.unshift(meta);store.set('closetMeta',arr);['itemName','itemTags'].forEach(id=>$('#'+id).value='');$('#photo').value='';toast('Added to closet.');renderCloset();renderReview()}
async function imageURL(id){const db=await dbp;return new Promise(res=>{const tx=db.transaction('images','readonly');const q=tx.objectStore('images').get(id);q.onsuccess=()=>res(q.result?URL.createObjectURL(q.result.blob):'')})}
async function renderCloset(){const arr=store.get('closetMeta',[]);const box=$('#closet');if(!box)return;box.innerHTML=arr.length?'':'<p class="muted">Add photos to build your outfit oracle.</p>';for(const item of arr){const url=await imageURL(item.id);const el=document.createElement('article');el.className='piece';el.innerHTML=`${url?`<img src="${url}">`:''}<div><strong>${item.name}</strong><br><span class="muted">${item.cat} · ${item.vibe}<br>${item.tags||''}</span><br><button class="ghost deletePiece" data-id="${item.id}">Remove</button></div>`;box.appendChild(el)}$$('.deletePiece').forEach(b=>b.onclick=()=>{store.set('closetMeta',store.get('closetMeta',[]).filter(x=>x.id!==b.dataset.id));renderCloset()})}
function buildOutfit(){const vibe=$('#oracleVibe').value,ctx=$('#oracleContext').value.toLowerCase();const arr=store.get('closetMeta',[]);const picks=arr.filter(x=>x.vibe===vibe||x.tags.toLowerCase().includes(vibe.toLowerCase()));const by=cat=>picks.find(x=>x.cat===cat)||arr.find(x=>x.cat===cat);const formula=vibes[vibe];let chosen=[by('Top'),by('Bottom'),by('Dress'),by('Outerwear'),by('Shoes'),by('Accessory'),by('Bag'),by('Full outfit')].filter(Boolean);if(!chosen.length){$('#outfitResult').innerHTML=`<div class="mini-item"><strong>${formula.emoji} ${vibe} formula</strong><br><span class="muted">${formula.armor}</span><br>Add closet photos and I can choose real pieces.</div>`;return}$('#outfitResult').innerHTML=`<div class="mini-item"><strong>${formula.emoji} ${vibe} outfit for ${ctx||'today'}</strong><br>${chosen.slice(0,5).map(x=>`${x.cat}: ${x.name}`).join('<br>')}<br><span class="muted">Finish: ${formula.armor}</span></div>`}
function exportData(){const data={local:{},closet:store.get('closetMeta',[])};Object.keys(localStorage).filter(k=>k.startsWith(LS)).forEach(k=>data.local[k]=localStorage.getItem(k));const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='queen-os-lifestyle-backup.json';a.click()}
function importData(e){const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const data=JSON.parse(rd.result);Object.entries(data.local||{}).forEach(([k,v])=>localStorage.setItem(k,v));toast('Imported. Reloading.');setTimeout(()=>location.reload(),800)}catch{toast('Import failed.')}};rd.readAsText(f)}
function setupInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();deferredPrompt=null;$('#installBtn').classList.add('hidden')}}
function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
window.addEventListener('load',init);